name: build mavpay 

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: report docs updated
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DOCS_BUILDER_ACCESS_TOKEN }}
          repository: tez-capital/bake.mavryk.org_builder
          event-type: subproject-updated
          client-payload: '{ "id": "${{ steps.repository_info.outputs.ID }}", "repository": "${{github.repository}}", "version": "${{github.ref_name}}"}'
